name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  hugo-pages:
    uses: cerberauth/ci/.github/workflows/hugo-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
